### ISSUE TITLE
Finish the refactoring of the three connectors for the pull request 

### ISSUE THREAD

**Issue by joseluisvf** [MariMountaineers/stream-reactor#26]
We must finish what we started in the three connectors that will serve as a proof of concept. This will be later reviewed by Stefan of DataMountaineer.

Depends on

- [] #27  Refactor hazelcast connector 
- [] #28  Refactor cassandra connector
- [] #29 Refactor rethink connector
